In [1]:
# This script combines all the datasets into one, Clean the data, Exploratory Data Analysis (EDA) and Text Pre-Processing

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load and add branch name for each DF
McDonald_Petronas_Kota_Damansara_DT = pd.read_excel("Dataset/Source/McDonald’s Petronas Kota Damansara DT.xlsx", sheet_name="Recovered_Sheet1")
McDonald_Petronas_Kota_Damansara_DT["Branch"] = "McDonald’s Petronas Kota Damansara DT"

McDonald_The_Mines = pd.read_excel("Dataset/Source/McDonald The Mines.xlsx", sheet_name="Recovered_Sheet1")
McDonald_The_Mines["Branch"] = "McDonald The Mines"

McDonald_Shell_Taman_Desa_DT = pd.read_excel("Dataset/Source/McDonald Shell Taman Desa DT.xlsx", sheet_name="Recovered_Sheet1")
McDonald_Shell_Taman_Desa_DT["Branch"] = "McDonald Shell Taman Desa DT"

McDonald_Shell_Saujana_Utama_DT = pd.read_excel("Dataset/Source/McDonald Shell Saujana Utama DT.xlsx", sheet_name="Recovered_Sheet1")
McDonald_Shell_Saujana_Utama_DT["Branch"] = "McDonald Shell Saujana Utama DT"

McDonald_Puchong_Perdana_SF = pd.read_excel("Dataset/Source/McDonald Puchong Perdana SF.xlsx", sheet_name="Recovered_Sheet1")
McDonald_Puchong_Perdana_SF["Branch"] = "McDonald Puchong Perdana SF"

McDonald_Desa_Petaling_SF = pd.read_excel("Dataset/Source/McDonald Desa Petaling SF.xlsx", sheet_name="Recovered_Sheet1")
McDonald_Desa_Petaling_SF["Branch"] = "McDonald Desa Petaling SF"

McDonald_BHP_Jalan_Genting_Kelang_DT_Store_476 = pd.read_excel("Dataset/Source/McDonald BHP Jalan Genting Kelang DT Store 476.xlsx", sheet_name="Recovered_Sheet1")
McDonald_BHP_Jalan_Genting_Kelang_DT_Store_476["Branch"] = "McDonald BHP Jalan Genting Kelang DT Store 476"

McDonald_AEON_BiG_Bukit_Rimau_DT = pd.read_excel("Dataset/Source/McDonald AEON BiG Bukit Rimau DT.xlsx", sheet_name="Recovered_Sheet1")
McDonald_AEON_BiG_Bukit_Rimau_DT["Branch"] = "McDonald AEON BiG Bukit Rimau DT"

In [4]:
# Concatenate all DF
df = pd.concat(
    [
        McDonald_Petronas_Kota_Damansara_DT,
        McDonald_The_Mines,
        McDonald_Shell_Taman_Desa_DT,
        McDonald_Shell_Saujana_Utama_DT,
        McDonald_Puchong_Perdana_SF,
        McDonald_Desa_Petaling_SF,
        McDonald_BHP_Jalan_Genting_Kelang_DT_Store_476,
        McDonald_AEON_BiG_Bukit_Rimau_DT
    ],
    axis=0
)
df.columns = McDonald_Petronas_Kota_Damansara_DT.columns

In [5]:
# 1. Data Cleaning

# Keep only the specified columns and rename them
df_cleaned = df[['Branch', 'd4r55', 'rsqaWe', 'wiI7pd']].copy()
df_cleaned.columns = ['Branch', 'Customer', 'Time', 'Reviews']

# Drop rows where all values are NaN
df_cleaned.dropna(how='all', inplace=True)

# Show the cleaned dataset
df_cleaned.head()

,Branch,Customer,Time,Reviews
0,McDonald’s Petronas Kota Damansara DT,Hamd,3 weeks ago,Worst McDonalds Ive visited in my life.\n\nFoo...
1,McDonald’s Petronas Kota Damansara DT,Megan Ooi,3 months ago,"worst service ever, when requested for chicken..."
2,McDonald’s Petronas Kota Damansara DT,VincentKoh LUMCFan,5 months ago,[2022-2024]\n\nAlways ALWAYS a pleasant locati...
3,McDonald’s Petronas Kota Damansara DT,Pang Choon Fuei,4 months ago,I done the kiosk order and pay Cash.\n\nBut em...
4,McDonald’s Petronas Kota Damansara DT,nur aein,3 months ago,"Please train your mc cafe staff, order ice ble..."

In [6]:
# Replace missing values with specified defaults
df_cleaned['Customer'] = df_cleaned['Customer'].fillna('Unknown')
df_cleaned['Time'] = df_cleaned['Time'].fillna('Unknown')
df_cleaned['Reviews'] = df_cleaned['Reviews'].fillna('No Review')
df_cleaned['Branch'] = df_cleaned['Branch'].fillna('Unknown')

In [7]:
df_cleaned.tail()

,Branch,Customer,Time,Reviews
80,McDonald AEON BiG Bukit Rimau DT,{lisa farnani},5 months ago,No Review
81,McDonald AEON BiG Bukit Rimau DT,Jeyakumaran Murughan,6 months ago,No Review
82,McDonald AEON BiG Bukit Rimau DT,Vinn 7,7 months ago,No Review
83,McDonald AEON BiG Bukit Rimau DT,Diella Othman,7 months ago,No Review
84,McDonald AEON BiG Bukit Rimau DT,Muhammad Fadzli bin A Rusli,8 months ago,No Review

In [8]:
# Checking for null values 
df_cleaned.isnull().sum()

Branch      0
Customer    0
Time        0
Reviews     0
dtype: int64

In [9]:
# Checking Duplicate values 
df_cleaned.duplicated().sum()

0

In [10]:
# 2. Exploratory Data Analysis (EDA)

df_cleaned.describe()

,Branch,Customer,Time,Reviews
count,920,920,920,920
unique,8,914,31,718
top,McDonald BHP Jalan Genting Kelang DT Store 476,Nik Hasif Nik Hasbollah,a year ago,No Review
freq,212,2,180,201

In [11]:
df_cleaned.groupby('Branch').describe()

                                               Customer         \
                                                  count unique
Branch
McDonald AEON BiG Bukit Rimau DT                     85     85
McDonald BHP Jalan Genting Kelang DT Store 476      212    212
McDonald Desa Petaling SF                           106    106
McDonald Puchong Perdana SF                         109    109
McDonald Shell Saujana Utama DT                      93     93
McDonald Shell Taman Desa DT                        158    158
McDonald The Mines                                  142    142
McDonald’s Petronas Kota Damansara DT                15     15

                                                                         Time  \
                                                               top freq count
Branch
McDonald AEON BiG Bukit Rimau DT                        Sylvia Hew    1    85
McDonald BHP Jalan Genting Kelang DT Store 476                SL O    1   212
McDonald Desa Petaling SF                                  Ee Rick    1   106
McDonald Puchong Perdana SF                                 Mizu.L    1   109
McDonald Shell Saujana Utama DT                 Taarany Asaithamby    1    93
McDonald Shell Taman Desa DT                           zi kang tan    1   158
McDonald The Mines                               Dodo Ki (Dodo ki)    1   142
McDonald’s Petronas Kota Damansara DT                         Hamd    1    15

                                                                          \
                                               unique           top freq
Branch
McDonald AEON BiG Bukit Rimau DT                   16  7 months ago   18
McDonald BHP Jalan Genting Kelang DT Store 476     17    a year ago   71
McDonald Desa Petaling SF                          13  3 months ago   35
McDonald Puchong Perdana SF                        18    a year ago   46
McDonald Shell Saujana Utama DT                    14    a year ago   41
McDonald Shell Taman Desa DT                       20  5 months ago   27
McDonald The Mines                                 22   5 years ago   26
McDonald’s Petronas Kota Damansara DT               7  4 months ago    4

                                               Reviews
                                                 count unique        top freq
Branch
McDonald AEON BiG Bukit Rimau DT                    85     70  No Review   16
McDonald BHP Jalan Genting Kelang DT Store 476     212    173  No Review   40
McDonald Desa Petaling SF                          106     95  No Review   12
McDonald Puchong Perdana SF                        109     75  No Review   35
McDonald Shell Saujana Utama DT                     93     73  No Review   21
McDonald Shell Taman Desa DT                       158    125  No Review   34
McDonald The Mines                                 142    103  No Review   40
McDonald’s Petronas Kota Damansara DT               15     13  No Review    3

In [12]:
# 3.Text Pre-Processing

# import library 
import re 
import string 
import nltk 
from nltk.corpus import stopwords
from textblob import TextBlob
import emoji

In [13]:
stop_words = stopwords.words('english') 
more_stopwords = ['u', 'im', 'c'] 
stop_words = stop_words + more_stopwords

In [14]:
stemmer = nltk.SnowballStemmer("english")

In [15]:
internet_slang = {
    "u": "you",
    "ur": "your",
    "pls": "please",
    "plz": "please",
    "thx": "thanks",
    "btw": "by the way",
    "idk": "i do not know",
    "imo": "in my opinion",
    "lmao": "laughing my ass off",
    "lol": "laughing out loud",
    "omg": "oh my god",
    "gr8": "great",
    "b4": "before",
    "cuz": "because",
    "cu": "see you",
    "tnx": "thanks",
    "tq": "thank you",
    "nvm": "never mind",
    "wanna": "want to",
    "gonna": "going to",
    "gotta": "got to",
    "ya": "yeah",
    "nah": "no",
    "ok": "okay",
    "kk": "okay",
    "bc": "because",
    "r": "are",
    "ya'll": "you all"
}

contractions = {
    "i'm": "i am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "i've": "i have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "i would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "i will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "can't": "cannot",
    "won't": "will not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "couldn't": "could not",
    "mustn't": "must not",
    "mightn't": "might not",
    "needn't": "need not"
}

In [16]:
def preprocess(text):
    # Lowercase
    text = text.lower()

    # Remove expressions and content in square brackets
    text = re.sub(r'\[.*?\]', '', text)

    # Remove URLs
    text = re.sub(r'http\S+\s*\S+', '', text)
    text = re.sub(r'www\.\S+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove emojis
    text = emoji.replace_emoji(text, replace='')

    # Replace internet slang
    for slang, replacement in internet_slang.items():
        text = re.sub(r'\b' + re.escape(slang) + r'\b', replacement, text)

    # Replace contractions
    for contraction, full in contractions.items():
        text = re.sub(r'\b' + re.escape(contraction) + r'\b', full, text)

    # Remove punctuation and special characters
    text = re.sub(r'[^\w\s]', '', text)

    # Remove numbers
    text = re.sub(r'\b\w*\d\w*\b', '', text)

    # Correct spelling mistakes using TextBlob
    text = str(TextBlob(text).correct())

    # Remove stopwords
    text = ' '.join(word for word in text.split() if word not in stop_words)

    # Stemming
    text = ' '.join(stemmer.stem(word) for word in text.split())

    return text

In [17]:
df_cleaned['Cleaned_Reviews'] = df_cleaned['Reviews'].apply(preprocess) 
df_cleaned.head(20)

,Branch,Customer,Time,Reviews,Cleaned_Reviews
0,McDonald’s Petronas Kota Damansara DT,Hamd,3 weeks ago,Worst McDonalds Ive visited in my life.\n\nFoo...,worst macdonald give visit life food cold hard...
1,McDonald’s Petronas Kota Damansara DT,Megan Ooi,3 months ago,"worst service ever, when requested for chicken...",worst servic ever request chicken part said ch...
2,McDonald’s Petronas Kota Damansara DT,VincentKoh LUMCFan,5 months ago,[2022-2024]\n\nAlways ALWAYS a pleasant locati...,alway alway pleasant locat enjoy train go copi...
3,McDonald’s Petronas Kota Damansara DT,Pang Choon Fuei,4 months ago,I done the kiosk order and pay Cash.\n\nBut em...,done risk order pay cash employe present see l...
4,McDonald’s Petronas Kota Damansara DT,nur aein,3 months ago,"Please train your mc cafe staff, order ice ble...",pleas train cafe staff order ice blend much fo...
5,McDonald’s Petronas Kota Damansara DT,Huck Phin Ch'ng,4 months ago,No WiFi unlike the sign,wife unlik sign
6,McDonald’s Petronas Kota Damansara DT,Reenthiyahchandran Nitiyah,2 months ago,":\n""The cashier Watie was very friendly and gr...",cashier kati friend greet smile
7,McDonald’s Petronas Kota Damansara DT,Syazwan Hilmi Shaharom,a month ago,They do not understand simple instructions and...,understand simpl instruct deliveri alway somet...
8,McDonald’s Petronas Kota Damansara DT,S jackey,2 months ago,"Hygienic issues, drinks with dirty objects",hygien issu drink dirti object
9,McDonald’s Petronas Kota Damansara DT,刘骏利,a month ago,Staffs are very nice here.,staff nice
10,McDonald’s Petronas Kota Damansara DT,Esa bin Abdul Shukor,a day ago,Worst ever McDonald's in Malaysia. Ordered thr...,worst ever macdonald malasha order thou show f...
11,McDonald’s Petronas Kota Damansara DT,Dom 999,4 months ago,Service is really out... Drive thru if it's th...,servic realli drive thou worst night q minut c...
12,McDonald’s Petronas Kota Damansara DT,Wong Cheng Leng,2 months ago,No Review,review
13,McDonald’s Petronas Kota Damansara DT,siti nur hidayah ismail,3 months ago,No Review,review
14,McDonald’s Petronas Kota Damansara DT,yusrie jumadi,4 months ago,No Review,review
0,McDonald The Mines,Dodo Ki (Dodo ki),8 months ago,Terrible attitude by the staff. I’m obviously ...,terribl attitud staff obvious say spice tomato...
1,McDonald The Mines,baby arrel,a month ago,Hope can improve.\nStaff many things don't kno...,hope improv staff mani thing know said sunday ...
2,McDonald The Mines,Iris Liew,2 months ago,"The wrong order was sent, and the staff called...",wrong order sent staff call replac order us wa...
3,McDonald The Mines,Pao Fook Seong,3 years ago,Everybody's favorite and it is everywhere. I ...,everybodi favorit everywher patron year ago bi...
4,McDonald The Mines,RANJITH Melvin,10 months ago,So my boyfriend and I went to this MCD which l...,boyfriend went mud locat mine shop mall order ...

In [18]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

# Initialize the lemmatizer and stemmer
lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()

# Define the stop words
stop_words = set(stopwords.words('english'))

In [19]:
# Function to perform stemming and lemmatization
def preprocess_text(text):
    tokens = word_tokenize(text.lower())  # Tokenize the text into words and convert to lowercase
    tokens = [token for token in tokens if token.isalnum()]  # Filter out non-alphanumeric tokens
    tokens = [token for token in tokens if token not in stop_words]  # Remove stopwords from the tokens
    tokens = [lemmatizer.lemmatize(token) for token in tokens]  # Lemmatize each token
    return tokens  # Return the preprocessed tokens

In [20]:
# Apply lemmatization and stemming
df_cleaned['Processed_Reviews'] = df_cleaned['Cleaned_Reviews'].apply(preprocess_text)  # Apply the function to each document

# Display the first 20 rows of the cleaned data
df_cleaned.head(20)

,Branch,Customer,Time,Reviews,Cleaned_Reviews,Processed_Reviews
0,McDonald’s Petronas Kota Damansara DT,Hamd,3 weeks ago,Worst McDonalds Ive visited in my life.\n\nFoo...,worst macdonald give visit life food cold hard...,"[worst, macdonald, give, visit, life, food, co..."
1,McDonald’s Petronas Kota Damansara DT,Megan Ooi,3 months ago,"worst service ever, when requested for chicken...",worst servic ever request chicken part said ch...,"[worst, servic, ever, request, chicken, part, ..."
2,McDonald’s Petronas Kota Damansara DT,VincentKoh LUMCFan,5 months ago,[2022-2024]\n\nAlways ALWAYS a pleasant locati...,alway alway pleasant locat enjoy train go copi...,"[alway, alway, pleasant, locat, enjoy, train, ..."
3,McDonald’s Petronas Kota Damansara DT,Pang Choon Fuei,4 months ago,I done the kiosk order and pay Cash.\n\nBut em...,done risk order pay cash employe present see l...,"[done, risk, order, pay, cash, employe, presen..."
4,McDonald’s Petronas Kota Damansara DT,nur aein,3 months ago,"Please train your mc cafe staff, order ice ble...",pleas train cafe staff order ice blend much fo...,"[plea, train, cafe, staff, order, ice, blend, ..."
5,McDonald’s Petronas Kota Damansara DT,Huck Phin Ch'ng,4 months ago,No WiFi unlike the sign,wife unlik sign,"[wife, unlik, sign]"
6,McDonald’s Petronas Kota Damansara DT,Reenthiyahchandran Nitiyah,2 months ago,":\n""The cashier Watie was very friendly and gr...",cashier kati friend greet smile,"[cashier, kati, friend, greet, smile]"
7,McDonald’s Petronas Kota Damansara DT,Syazwan Hilmi Shaharom,a month ago,They do not understand simple instructions and...,understand simpl instruct deliveri alway somet...,"[understand, simpl, instruct, deliveri, alway,..."
8,McDonald’s Petronas Kota Damansara DT,S jackey,2 months ago,"Hygienic issues, drinks with dirty objects",hygien issu drink dirti object,"[hygien, issu, drink, dirti, object]"
9,McDonald’s Petronas Kota Damansara DT,刘骏利,a month ago,Staffs are very nice here.,staff nice,"[staff, nice]"
10,McDonald’s Petronas Kota Damansara DT,Esa bin Abdul Shukor,a day ago,Worst ever McDonald's in Malaysia. Ordered thr...,worst ever macdonald malasha order thou show f...,"[worst, ever, macdonald, malasha, order, thou,..."
11,McDonald’s Petronas Kota Damansara DT,Dom 999,4 months ago,Service is really out... Drive thru if it's th...,servic realli drive thou worst night q minut c...,"[servic, realli, drive, thou, worst, night, q,..."
12,McDonald’s Petronas Kota Damansara DT,Wong Cheng Leng,2 months ago,No Review,review,[review]
13,McDonald’s Petronas Kota Damansara DT,siti nur hidayah ismail,3 months ago,No Review,review,[review]
14,McDonald’s Petronas Kota Damansara DT,yusrie jumadi,4 months ago,No Review,review,[review]
0,McDonald The Mines,Dodo Ki (Dodo ki),8 months ago,Terrible attitude by the staff. I’m obviously ...,terribl attitud staff obvious say spice tomato...,"[terribl, attitud, staff, obvious, say, spice,..."
1,McDonald The Mines,baby arrel,a month ago,Hope can improve.\nStaff many things don't kno...,hope improv staff mani thing know said sunday ...,"[hope, improv, staff, mani, thing, know, said,..."
2,McDonald The Mines,Iris Liew,2 months ago,"The wrong order was sent, and the staff called...",wrong order sent staff call replac order us wa...,"[wrong, order, sent, staff, call, replac, orde..."
3,McDonald The Mines,Pao Fook Seong,3 years ago,Everybody's favorite and it is everywhere. I ...,everybodi favorit everywher patron year ago bi...,"[everybodi, favorit, everywher, patron, year, ..."
4,McDonald The Mines,RANJITH Melvin,10 months ago,So my boyfriend and I went to this MCD which l...,boyfriend went mud locat mine shop mall order ...,"[boyfriend, went, mud, locat, mine, shop, mall..."

In [21]:
# Save the cleaned DataFrame to a new Excel file
df_cleaned.to_excel("Dataset/Pre-Text Processing Dataset.xlsx", index=False)